---
- name: (playbook-project-prod) create project prod
  hosts: all
  roles:
    - takel-base
    - takel-users
    - takel-ssh
    - takel-bit-client
    - takel-bit-server
    - role: takel-gcsfuse
      when: takel_gcsfuse_gcs_bucket_key is defined
      # takel-gcsfuse needs to be called after takel-bit-server
    - takel-cleanup
